# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JLiJHXJZzaByvuIzurgNybGFs_ud-Jup
"""

!pip install python-docx
!pip install docx
!pip install nltk
import spacy
import nltk
!pip install spacy==2.3.7
!pip install spacytextblob
nltk.download('stopwords')
!python -m textblob.download_corpora

from spacytextblob.spacytextblob import SpacyTextBlob
nlp = spacy.load('en_core_web_sm')
nlp.add_pipe("spacytextblob")


!pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.7/en_core_web_sm-2.3.7.tar.gz




!pip install pyresparser




from pyresparser import ResumeParser
import os
from docx import Document

filed = input()


try:
    doc = Document()
    with open(filed, 'r') as file:
        doc.add_paragraph(file.read())
    doc.save("text.docx")
    data = ResumeParser('text.docx').get_extracted_data()
    print(data['skills'])
except:
    data = ResumeParser(filed).get_extracted_data()
    print(data['skills'])

#Installation
!pip install pyresparser

# spaCy
!python -m spacy download en_core_web_sm

 # nltk
!python -m nltk.downloader words

#Upload the file 
file = input()

import nltk
nltk.download('stopwords')


#Utilisation
from pyresparser import ResumeParser
data = ResumeParser(file).get_extracted_data()